version: "3"
services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_DB: "hpostgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"